export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS'
// export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
// export const RECEIVE_USERS = 'RECEIVE_USERS'
// export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS'
